version: "3.9"
services:
    web:
        image: edmilsonexpedito2305/byecar-image:latest
        container_name: web
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            args:
                PHP_VERSION: "8.3.3-fpm-bullseye"
        # volumes:
        #     - ./app:/var/www/app
        ports:
            - "8080:80" #http
            - "443:443" #https
