name: Build and Push Image to DockerHub
on:
    push:
        branches: [develop]

jobs:
    build-and-push:
        name: Build and Push to DockerHub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Automatic Tagging of Releases
              id: increment-git-tag
              run: |
                  bash ./build/git_update.sh -v minor
                  echo "GIT_TAG=${{ steps.increment-git-tag.outputs.git-tag }}" >> $GITHUB_ENV

            - name: Build and Push Image to DockerHub
              id: build-and-push
              env:
                  IMAGE_NAME: "edmilsonexpedito2305/byecar-image"
                  IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
              run: |
                  cd docker
                  docker build --no-cache -t $IMAGE_NAME:$IMAGE_TAG .
                  docker push $IMAGE_NAME:$IMAGE_TAG
